const FilterData = [
  {
    id: 12,
    userImg: require("../assets/FilterData/eva-irfan.png"),
    category: "Ekslusif",
    img1: require("../assets/FilterData/irfan.jpg"),
    img2: require("../assets/FilterData/eva.jpg"),
    userName: "Irfan & Eva",
    viewUser: 732,
    style: "bg-yellow-500",
  },
  {
    id: 5,
    userImg: require("../assets/FilterData/dr-syifa-dr-riki.png"),
    category: "Ekslusif",
    img1: require("../assets/FilterData/dr-riki.jpg"),
    img2: require("../assets/FilterData/dr-syifa.jpg"),
    userName: "dr. Riki & dr. Syifa",
    viewUser: 261,
    style: "bg-yellow-500",
  },
  {
    id: 1,
    userImg: require("../assets/FilterData/ricky-putri.png"),
    category: "Ekslusif",
    img1: require("../assets/FilterData/ricky.jpg"),
    img2: require("../assets/FilterData/putri.jpg"),
    userName: "Ricky & Putri",
    viewUser: 506,
    style: "bg-yellow-500",
  },
  {
    id: 8,
    userImg: require("../assets/FilterData/indry-gulid.png"),
    category: "Ekslusif",
    img1: require("../assets/FilterData/gulid.jpg"),
    img2: require("../assets/FilterData/indry.jpg"),
    userName: "Gulid & Indry",
    viewUser: 689,
    style: "bg-yellow-500",
  },
  {
    id: 2,
    userImg: require("../assets/FilterData/rossa-ramadhianty&riyan-alfarizki.png"),
    category: "Basic",
    img1: require("../assets/FilterData/riyan-alfarizki.jpg"),
    img2: require("../assets/FilterData/rossa-ramadhianty.jpg"),
    userName: "Riyan Alfarizki & Rossa Ramadhianty",
    viewUser: 9625,
    style: "bg-green-500",
  },
  {
    id: 11,
    userImg: require("../assets/FilterData/aisy&alqarny.png"),
    category: "Basic",
    img1: require("../assets/FilterData/aisy.jpg"),
    img2: require("../assets/FilterData/alqarny.jpg"),
    userName: "Aisy & Alqarny",
    viewUser: 3170,
    style: "bg-green-500",
  },
  {
    id: 10,
    userImg: require("../assets/FilterData/wilis&shierly.png"),
    category: "Basic",
    img1: require("../assets/FilterData/shierly.jpg"),
    img2: require("../assets/FilterData/wilis.jpg"),
    userName: "Shierly & Wilis",
    viewUser: 2145,
    style: "bg-green-500",
  },
  {
    id: 4,
    userImg: require("../assets/FilterData/ayu&apit.png"),
    category: "Basic",
    img1: require("../assets/FilterData/apit.jpg"),
    img2: require("../assets/FilterData/ayu.jpg"),
    userName: "Apit & Ayu",
    viewUser: 1694,
    style: "bg-green-500",
  },
  {
    id: 9,
    userImg: require("../assets/FilterData/susi-irfan.png"),
    category: "Premium",
    img1: require("../assets/FilterData/irfan2.jpg"),
    img2: require("../assets/FilterData/susi.jpg"),
    userName: "Irfan & Susi",
    viewUser: 1254,
    style: "bg-red-600",
  },
  {
    id: 7,
    userImg: require("../assets/FilterData/santi&andri.png"),
    category: "Premium",
    img1: require("../assets/FilterData/andri.jpg"),
    img2: require("../assets/FilterData/santi.jpg"),
    userName: "Andri & Santi",
    viewUser: 8643,
    style: "bg-red-600",
  },
  {
    id: 6,
    userImg: require("../assets/FilterData/fatra&dinda.png"),
    category: "Premium",
    img1: require("../assets/FilterData/fatra.jpg"),
    img2: require("../assets/FilterData/dinda.jpg"),
    userName: "Dinda & Fatra",
    viewUser: 3549,
    style: "bg-red-600",
  },
  {
    id: 3,
    userImg: require("../assets/FilterData/rika&aziz.png"),
    category: "Premium",
    img1: require("../assets/FilterData/aziz.jpg"),
    img2: require("../assets/FilterData/rika.jpg"),
    userName: "Aziz & Rika",
    viewUser: 1199,
    style: "bg-red-600",
  },
];

export default FilterData;
